# group_vars/all.yml
# ---

# override default, system python in order to use python in venv
ansible_python_interpreter: python3

# IP Address to allow access for SSH & PostgreSQL from:
home_ip: 98.116.39.58

org_name: roja
service_name: elektron

https_domain_name: "{{service_name}}.photos"
application_domain_name: "{{https_domain_name}}"
media_cname: "media.{{https_domain_name}}"
media_upload_bucket_name: "{{service_name}}-media"
media_processor_artifact_bucket_name: "{{service_name}}-archive"
static_files_bucket_name: "{{service_name}}-static"

# EC2 Facts
nat_instance_ami: ami-058436d7e072250b3
nat_instance_type: t2.micro

## Lambda deployment & config
photo_processor_rolename: elektron-production-photoProcessorRole
photo_processor_connection_timeout: 5
photo_processor_memory_size: 256

# DB Facts
rds_instance_name: elektron-db
rds_database_name: media_info
rds_master_username: elektrondba
rds_app_username: elektronusr

# AWS Facts
aws_ssh_key: roja-llc
aws_region: us-east-1

## Django Configuration
django_debug_enabled: False
django_email_backend: django.core.mail.backends.filebased.EmailBackend
django_allowed_hosts: "{{ application_domain_name }},.execute-api.us-east-1.amazonaws.com"

## VPC Configuration

vpc_cidr_block: 10.0.0.0/16

vpc_subnets:
  private-01:
    cidr: 10.0.0.0/19
    az: "{{ aws_region }}a"
    visibility: private
  public-01:
    cidr: 10.0.32.0/19
    az: "{{ aws_region }}a"
    visibility: public
  private-02:
    cidr: 10.0.64.0/19
    az: "{{ aws_region }}b"
    visibility: private
  public-02:
    cidr: 10.0.96.0/19
    az: "{{ aws_region }}b"
    visibility: public

vpc_subnets_private: 
  - "{{vpc_subnets['private-01']['cidr']}}"
  - "{{vpc_subnets['private-02']['cidr']}}"
vpc_subnets_public: 
  - "{{vpc_subnets['public-01']['cidr']}}"
  - "{{vpc_subnets['public-02']['cidr']}}"
