# group_vars/all.yml
# ---

# override default, system python in order to use python in venv
ansible_python_interpreter: python3

# IP Address to allow access for SSH & PostgreSQL from:
home_ip: 98.116.39.58

service_name: elektrum

aws_region: us-east-1

config_info: "../etc/env/{{operating_env}}.env"

# Domain names
media_cname: "media.{{application_domain_name}}"
static_cname: "static.{{application_domain_name}}"

# S3 Facts
media_upload_bucket_name: "{{service_name}}-{{ operating_env }}-media"
media_processor_artifact_bucket_name: "{{service_name}}-{{ operating_env }}-archive"
static_files_bucket_name: "{{service_name}}-{{ operating_env }}-static"

# Django Facts
django_email_backend: django.core.mail.backends.filebased.EmailBackend
django_allowed_hosts: "{{ application_domain_name }},.execute-api.us-east-1.amazonaws.com,127.0.0.1,localhost"

# RDS Facts
rds_database_name: media_info
rds_instance_name: "{{service_name}}-{{operating_env}}-db"
rds_master_username: "{{service_name}}_{{operating_env}}_dba"
rds_app_username: "{{service_name}}_{{operating_env}}_usr"

# EC2 Facts
aws_ssh_key: "{{service_name}}-{{operating_env}}"
nat_instance_ami: ami-058436d7e072250b3
nat_instance_type: t2.micro

## Lambda deployment & config
lambda_execution_rolename: "{{service_name}}-{{operating_env}}-LambdaExecutionRole" 
photo_processor_rolename: "{{service_name}}-{{operating_env}}-PhotoProcessorRole"
photo_processor_connection_timeout: 30
photo_processor_memory_size: 256
api_gateway_logging_rolename: "{{service_name}}-{{operating_env}}-APIGatewayLoggingRole"

## VPC Configuration
vpc_name: "{{service_name}}-{{operating_env}}-vpc"

vpc_subnets_private: 
  - "{{vpc_subnets['private-01']['cidr']}}"
  - "{{vpc_subnets['private-02']['cidr']}}"
vpc_subnets_public: 
  - "{{vpc_subnets['public-01']['cidr']}}"
  - "{{vpc_subnets['public-02']['cidr']}}"
