---
- name: 'create a public zone for {{ https_domain_name }}'
  route53_zone:
    zone: '{{ https_domain_name }}'
    comment: '{{ https_domain_name }} public zone'
  register: hosted

- debug: var=hosted

# The value for `alias_hosted_zone_id` is hardcoded to that specific value, for reference see docs on this here:
# https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/route53.html#Route53.Client.change_resource_record_sets
- name: add alias records to this zone
  route53:
    alias: True
    alias_hosted_zone_id: Z2FDTNDATAQYW2
    hosted_zone_id: "{{ hosted.zone_id }}"
    record: "{{ item.dn }}"
    state: present
    overwrite: True
    type: A
    value: "{{ item.cdn }}"
    zone: '{{ https_domain_name }}'
  with_items:
    - "{{ dns_info }}"
