# Generated by Django 2.1.5 on 2019-02-09 17:37

import albums.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0003_auto_20190125_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('path', models.CharField(help_text='Required. Path to media album within the album.', max_length=1024, validators=[albums.models.AlbumPathValidator()], verbose_name='album path')),
                ('collection', models.ForeignKey(help_text='Collection this album is part of', on_delete=django.db.models.deletion.CASCADE, to='collection.Collection')),
                ('user', models.ForeignKey(help_text='User that owns this album', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('path', 'user')},
        ),
    ]
