FROM python:3.7 AS base

RUN mkdir -p /app/project
RUN mkdir -p /app/static
RUN mkdir -p /app/etc

ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    POETRY_VERSION=0.12.11

## poetry version should agree with version in pyproject.toml
RUN pip install 'poetry==0.12.11'
WORKDIR /app
COPY pyproject.toml poetry.lock /app

RUN poetry config settings.virtualenvs.create false &&
    poetry install --no-dev --no-ansi --no-interaction

FROM base AS release

ARG ELEKTRON_ENV=production

ADD project /app/project
ADD static /app/static
COPY etc/${ELEKTRON_ENV}.env /app/etc
COPY version.txt /app
COPY docker-entrypoint.sh /app

RUN chmod +x /app/docker-entrypoint.sh

EXPOSE 8000

ENTRYPOINT [ "/app/docker-entrypoint.sh" ]
