#!/bin/zsh

set -e

envs=(
  development
  staging
  production
)

OPERATING_ENV=${1}

if [ -z "${OPERATING_ENV}" ];
then
    OPERATING_ENV='development'
else
    shift
fi

if ! ((envs[(Ie)$OPERATING_ENV])); then
  printf "Usage: ${0} ENV [TASKS]\n\tENVs: [development|staging|production]\n"
  exit 1
fi

export OPERATING_ENV
export PYTHONPATH=${PYTHONPATH}:$(pwd)/tools
export PATH=${PATH}:${VIRTUAL_ENV}/bin
export ANSIBLE_FORCE_COLOR=1

doit --failure-verbosity=2 --process=4 --parallel-type=process ${@}
