#!/bin/zsh

function main() {
    log "Generating pip-style requirements.txt."
    etc/bin/poetry2pip.py poetry.lock > requirements.txt

    log "Bundling lambda code into a zip archive."
    lambda_archive=$(lgw lambda-archive ${VERBOSE} --config-file=${CONFIG})

    log "Deploying lambda archive from location: ${lambda_archive}"
    lgw lambda-deploy ${VERBOSE} --config-file=${CONFIG} --lambda-file=${lambda_archive}

    log "Creating an API gateway for this function, if it doesn't already exist."
    lgw gw-deploy ${VERBOSE} --config-file=${CONFIG}

    log "Linking domain name with this gateway."
    api_url=$(lgw domain-add ${VERBOSE} --config-file=${CONFIG})

    apply_migrations

    deploy_static_assets

    log "Application deployed at URL: ${api_url}"
}

function log() {
    msg=$1
    now=$(date +"%Y/%m/%d %H:%M:%S")
    echo "[${now}][BASH] ${msg}"
}

function check_required() {
    command -v jq >/dev/null 2>&1 || { echo >&2 "Command 'jq' not installed. Install using `brew install jq`.  Aborting."; exit 1; }
    command -v yq >/dev/null 2>&1 || { echo >&2 "Command 'yq' not installed. Install using `brew install yq`.  Aborting."; exit 1; }
    command -v aws >/dev/null 2>&1 || { echo >&2 "Command 'aws' not installed. Install using `brew install awscli`.  Aborting."; exit 1; }
    command -v ansible-vault >/dev/null 2>&1 || { echo >&2 "Command 'ansible-vault' not installed. Install using `brew install ansible`.  Aborting."; exit 1; }
}

function deploy_static_assets() {
    log "Deploying static assets."
    make static
}

function apply_migrations() {
    log "Applying database migrations."

    source ${CONFIG}

    output_file=$(mktemp)
    trap "{ rm -f $output_file; }" EXIT

    aws --output json \
        lambda invoke \
        --function-name ${AWS_LAMBDA_NAME} \
        --log-type Tail \
        --payload '{"manage": {"cmd": "migrate"} }' ${output_file} \
    | jq --raw-output .LogResult | base64 --input=- --decode
}

function create_admin_user() {
    log "Creating admin user account."

    django_admin_username=`yq read network/group_vars/${ENV}.yml 'django_admin_username' | ansible-vault decrypt --vault-password-file=network/environments/${ENV}-vault-password.txt`
    django_admin_password=`yq read network/group_vars/${ENV}.yml 'django_admin_password' | ansible-vault decrypt --vault-password-file=network/environments/${ENV}-vault-password.txt`

    dummy_email='admin@example.com'

    source ${CONFIG}

    output_file=$(mktemp)
    trap "{ rm -f $output_file; }" EXIT

event=$(cat <<-EOT
{
    "manage": {
        "cmd": "create-admin-user",
        "args": {
            "username": "${django_admin_username}",
            "password": "${django_admin_password}",
            "email": "${dummy_email}"
        }
    }
}
EOT
)

    aws --output json \
        lambda invoke \
        --function-name ${AWS_LAMBDA_NAME} \
        --log-type Tail \
        --payload "${event}" ${output_file} \
    | jq --raw-output .LogResult | base64 --input=- --decode
}

log "Ensuring required commands are installed."
check_required

ENV=
VERBOSE=

while true; do
    case "$1" in
    -v|--verbose)
        VERBOSE=--verbose
        shift;
        ;;
    development|staging|production)
        ENV=$1
        shift
        ;;
    static|migrate|admin-user)
        CMD=$1
        shift
        ;;
    *)
        break
        ;;
    esac
done

if [ -z "${ENV}" ];
then
  echo "Usage: $0 [development|staging|production] (static|migrate|admin-user)"
  exit 1
fi

CONFIG="etc/env/${ENV}.env"
VERSION=$(cat version.txt | tr -d '\n')
CWD=$(pwd)

export AWS_ACCESS_KEY_ID=`yq read network/group_vars/${ENV}.yml 'aws_access_key' | ansible-vault decrypt --vault-password-file=network/environments/${ENV}-vault-password.txt`
export AWS_SECRET_ACCESS_KEY=`yq read network/group_vars/${ENV}.yml 'aws_secret_key' | ansible-vault decrypt --vault-password-file=network/environments/${ENV}-vault-password.txt`
export AWS_LAMBDA_ARCHIVE_KEY="elektrum-${VERSION}.zip"

log "Building Elektrum release v${VERSION}."
log "    Environment:   ${ENV}"
log "    Configuration: ${CONFIG}"
log "    Current dir:   ${CWD}"

case "$CMD" in
static)
    deploy_static_assets
    ;;
migrate)
    apply_migrations
    ;;
admin-user)
    create_admin_user
    ;;
*)
    main "$@"
    ;;
esac
