[tool.poetry]
name = "elektrum"
version = "0.24.dev0"
description = "Media archiving & management system."
authors = ["Edward Q. Bridges <ebridges@roja.cc>"]
readme = "README.md"
homepage = "https://elektrum.photos"
repository = "https://bitbucket.org/roja-cc/elektrum"
license = "CC-BY-NC-ND-4.0"

[tool.poetry.dependencies]
python = "^3.6"
django = "^2.1.3"
django-allauth = "^0.38.0"
gunicorn = "^19.9.0"
django-dotenv = "^1.4.2"
psycopg2-binary = "^2.7.7"
boto3 = "^1.9.106"
zappa = "^0.48.2"
django-sslserver = "^0.20.0"
django-storages = "^1.7"

[tool.poetry.dev-dependencies]
pylint = "^2.3.1"
ansible = { git = "https://github.com/ansible/ansible.git", rev = "d77697e" }
ansible-vault = "^1.2.0"
botocore = "^1.12.106"
boto = "^2.49.0"
zest-releaser = "^6.17.0"
selenium = "^3.141.0"
coverage = "^4.5.1"
factory-boy = "^2.11.1"
pytest = "4.0.1"
pytest-django = "^3.4.4"
pytest-cov = "^2.6.0"
pytest-factoryboy = "^2.0.2"
records = "^0.5.3"
virtualenvwrapper = "^4.8.4"
assertpy = "^0.14.0"
jinja2 = "^2.10"
cryptography = "^2.7"
jmespath-terminal = "^0.2.1"
autopep8 = "^1.4"
logging_tree = "^1.8"

[build-system]
## poetry version should agree with version in Dockerfile-App
requires = ["poetry==0.12.11"]
build-backend = "poetry.masonry.api"
