# Generated by Django 2.1.7 on 2019-04-06 01:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media_items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(model_name='mediaitem', old_name='path', new_name='file_path'),
        migrations.AddField(
            model_name='mediaitem',
            name='aperture',
            field=models.CharField(
                help_text='Optional. The lens aperture setting used when this media item was created.',
                max_length=64,
                null=True,
                verbose_name='aperture',
            ),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='camera_make',
            field=models.CharField(
                help_text='Optional. Name of the camera used for creating this media item.',
                max_length=64,
                null=True,
                verbose_name='camera make',
            ),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='camera_model',
            field=models.CharField(
                help_text='Optional. Model of the camera used for creating this media item.',
                max_length=64,
                null=True,
                verbose_name='camera model',
            ),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='create_date',
            field=models.DateTimeField(
                default=None,
                help_text='Required. The date and time this media item was created.',
                verbose_name='artist',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='file_size',
            field=models.BigIntegerField(
                default=0,
                help_text='Required. The size in bytes of the media item.',
                verbose_name='artist',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='focal_length_denominator',
            field=models.IntegerField(
                help_text='Optional. The focal length (denominator) setting used when this media item was created.',
                null=True,
                verbose_name='focal length (denominator)',
            ),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='focal_length_numerator',
            field=models.IntegerField(
                help_text='Optional. The focal length (numerator) setting used when this media item was created.',
                null=True,
                verbose_name='focal length (numerator)',
            ),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='gps_alt',
            field=models.FloatField(
                help_text='Optional. The altitude of the GPS location of where this media item was created.',
                null=True,
                verbose_name='gps altitude',
            ),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='gps_date_time',
            field=models.DateTimeField(
                help_text='Optional. The date and time in UTC at the GPS location of where this media item was created.',
                null=True,
                verbose_name='gps date time',
            ),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='gps_lat',
            field=models.FloatField(
                help_text='Optional. The latitude of the GPS location of where this media item was created.',
                null=True,
                verbose_name='gps latitude',
            ),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='gps_lon',
            field=models.FloatField(
                help_text='Optional. The longitude of the GPS location of where this media item was created.',
                null=True,
                verbose_name='gps longitude',
            ),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='image_height',
            field=models.IntegerField(
                default=0,
                help_text='Required. The height of this media item.',
                verbose_name='image height',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='image_width',
            field=models.IntegerField(
                default=0,
                help_text='Required. The width of this media item.',
                verbose_name='image width',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='iso_speed',
            field=models.IntegerField(
                help_text='Optional. The ISO speed of the exposure used to create this media item.',
                null=True,
                verbose_name='iso speed',
            ),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='shutter_speed_denominator',
            field=models.IntegerField(
                help_text='Optional. The shutter speed (denominator) setting used when this media item was created.',
                null=True,
                verbose_name='shutter speed (denominator)',
            ),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='shutter_speed_numerator',
            field=models.IntegerField(
                help_text='Optional. The shutter speed (numerator) setting used when this media item was created.',
                null=True,
                verbose_name='shutter speed (numerator)',
            ),
        ),
        migrations.AlterUniqueTogether(name='mediaitem', unique_together={('file_path', 'owner')}),
    ]
