# Generated by Django 2.1.7 on 2019-05-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('media_items', '0004_auto_20190422_0004')]

    operations = [migrations.AlterUniqueTogether(name='mediaitem', unique_together=set())]
