# RDS / PostgreSQL Facts

rds_subnet_group_name: "{{ db_instance_name }}-sg"
rds_parameter_group_name: "{{ db_instance_name }}-pg"

rds_instance_type: db.m3.medium

rds_listen_port: 5432
rds_max_connections: 100
rds_shared_buffers: 55706 # '{DBInstanceClassMemory/32768}'
rds_effective_cache_size: 167117 # '{DBInstanceClassMemory*75/819200}'
rds_work_mem: 17826 # '{DBInstanceClassMemory/102400}' # rds_max_connections * 1024 = 102400
rds_storage_size: 100
