
- name: Create task definition
  ecs_taskdefinition:
    family: "{{ svc_task_family }}"
    containers: "{{ svc_task_containers }}"
    launch_type: EC2
    state: present
    network_mode: bridge
  register: task_output

- debug: var=task_output

- name: Create service to execute task
  ecs_service:
    state: present
    name: "{{ svc_name }}"
    region: "{{ aws_region }}"
    cluster: "{{ ecs_name }}"
    task_definition: '{{ svc_task_family }}'
    desired_count: "{{ svc_desired_count }}"
    deployment_configuration:
      minimum_healthy_percent: "{{ svc_min_healthy_percent }}"
      maximum_percent: "{{ svc_max_percent }}"
    # network_configuration:
    #   subnets: "{{ subnet_ids }}"
    #   security_groups: "{{ security_group_ids }}"
    load_balancers:
      - containerName: "{{ svc_container_name }}"
        containerPort: "{{ svc_container_port }}"
        loadBalancerName: "{{ elb_name }}"
