---
- block:
    - include_tasks: setup.ecr.yml
    - include_tasks: setup.task.yml
    - include_tasks: setup.service.yml
  when: ecs_state == "present"

- block:
    - include_tasks: drop.service.yml

    - name: Drop task definition
      ecs_taskdefinition:
        arn: "{{ task_arn }}"
        state: absent
      register: task_output

    - debug: var=task_output

    # - name: Drop container repository
    #   ecs_ecr: 
    #     name: '{{ org_name }}/{{ service_name }}-service'
    #     state: absent
    #   register: task_output

    # - debug: var=task_output
  when: ecs_state == "absent"
