# - debug: 
#     msg: "logging: {{logging_namespace}}"

- name: Configure container(s)
  set_fact:
    svc_task_containers:
      - name: "{{ svc_proxy_container }}"
        essential: true
        image: nginx:1.13
        portMappings:
          - containerPort: "{{ svc_container_port }}"
            hostPort: "{{ svc_container_port }}"
            protocol: "tcp"
        memoryReservation: "{{ svc_container_mem }}"
        logConfiguration:
          logDriver: awslogs
          options:
            awslogs-group: "{{ logging_namespace }}"
            awslogs-region: "{{ aws_region }}"
      - name: "{{ svc_app_container }}"
        essential: true
        image: "{{ repository_uri }}:latest"
        memoryReservation: "{{ svc_container_mem }}"
        logConfiguration:
          logDriver: awslogs
          options:
            awslogs-group: "{{ logging_namespace }}"
            awslogs-region: "{{ aws_region }}"

- name: Create task definition
  ecs_taskdefinition:
    family: "{{ svc_name }}"
    containers: "{{ svc_task_containers }}"
    launch_type: EC2
    state: present
    network_mode: bridge
    task_role_arn: "{{ ecs_instance_iam_role }}"
    execution_role_arn: "{{ ecs_instance_iam_role }}"
  register: task_output

- debug: var=task_output
