# - name: "Configure role with services needed for ECS"
#   iam_role:
#     name: "{{ ecs_instance_iam_role }}"
#     description: "Role for EC2 instances that are part of EC2 clusters"
#     assume_role_policy_document: "{{ lookup('file', 'iam_trust_policy.json')  }}"
#     managed_policy:
#       - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
#       - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole
#     state: present
#   register: iam_machine_role

# - debug: var=iam_machine_role verbosity=2

- elb_target_group_facts:
    names: 
      - "{{ elb_target_group_name }}"
  register: elb_tg_info

- debug: var=elb_tg_info

- name: Create service to execute task
  ecs_service:
    state: present
    name: "{{ svc_name }}"
    region: "{{ aws_region }}"
    cluster: "{{ ecs_name }}"
    task_definition: '{{ svc_task_family }}'
    desired_count: "{{ svc_desired_count }}"
    deployment_configuration:
      minimum_healthy_percent: "{{ svc_min_healthy_percent }}"
      maximum_percent: "{{ svc_max_percent }}"
    # network_configuration:
    #   subnets: "{{ subnet_ids }}"
    #   security_groups: "{{ security_group_ids }}"
    load_balancers:
      - containerName: "{{ svc_container_name }}"
        containerPort: "{{ svc_container_port }}"
        targetGroupArn: "{{ elb_tg_info.target_groups[0].target_group_arn }}"
