- name: Get the current caller identity facts
  aws_caller_info:
  register: caller_info

- set_fact: aws_account_id={{ caller_info.account }}

- debug: var=caller_info verbosity=3

- name: Add policy that allows this lambda to be invoked by the upload bucket in S3
  lambda_policy:
    state: "present"
    action: lambda:InvokeFunction
    principal: s3.amazonaws.com
    function_name: "{{ media_processor_lambda_name }}"
    statement_id: "{{ media_processor_execution_role_policy }}"
    source_arn: "arn:aws:s3:{{aws_region}}:{{aws_account_id}}:{{ media_upload_bucket_name }}"
    source_account: "{{aws_account_id}}"
  register: lambda_policy

- debug: var=lambda_policy verbosity=3

- name: Link up image processor lambda with media upload bucket.
  s3_bucket_notification:
    state: present
    event_name: on_object_create
    suffix: .jpg
    events: ["s3:ObjectCreated:*", "s3:ObjectRemoved:*"]
    bucket_name: "{{ media_upload_bucket_name }}"
    lambda_function_arn: "{{ media_processor_lambda_arn }}"
  register: bucket_notification

- debug: var=bucket_notification verbosity=3
