## BEGIN
## queries the CNAME hosts and the CDN domain names in
## order to build a simplified map of cname : domain name.

query: '{dn: cloudfront.summary.distributions[*].Aliases[*], cdn: cloudfront.summary.distributions[*].DomainName}'
lists: '{{ cdn_facts | json_query(query) }}'

# {
#     "dicts": {
#         "d321f26luq1ktv.cloudfront.net": [
#             "elektrum.photos",
#             "www.elektrum.photos"
#         ],
#         "dccm9m7oagekp.cloudfront.net": [
#             "media.elektrum.photos"
#         ]
#     }
# }
dicts: '{{ dict( lists.cdn | zip_longest(lists.dn) ) }}'

# {
#     "dns_info": [
#         {
#             "cdn": "dccm9m7oagekp.cloudfront.net",
#             "dn": "media.elektrum.photos"
#         },
#         {
#             "cdn": "d321f26luq1ktv.cloudfront.net",
#             "dn": "elektrum.photos"
#         },
#         {
#             "cdn": "d321f26luq1ktv.cloudfront.net",
#             "dn": "www.elektrum.photos"
#         }
#     ]
# }
dns_info: |
  {% set res = [] -%}
  {%- for (key,values) in dicts.items() -%}
    {%- for item in values -%}

    {% set ignored = res.extend([{
      "dn": item,
      "cdn": key
      }]) -%}

    {%- endfor %}
  {%- endfor %}
  {{ res }}

## END
