version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv ./project/venv
            . ./project/venv/bin/activate
            python -m pip install --upgrade pip
            python -m pip install toml
            etc/bin/poetry2pip.py --file poetry.lock --dev-deps > requirements.txt
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            . ./project/venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          working_directory: ./project
          command: |
            . venv/bin/activate
            python3 manage.py test
