# host_vars/elektron.vpc.yml

vpc_name: elektron-vpc
vpc_key: elektron-key
vpc_dns_zone: elektron-dns

vpc_cidr_block: 10.0.0.0/16

vpc_subnets:
  private-01:
    cidr: 10.0.1.0/24
    az: "{{ aws_region }}a"
  public-01:
    cidr: 10.0.2.0/24
    az: "{{ aws_region }}a"
  private-02:
    cidr: 10.0.3.0/24
    az: "{{ aws_region }}b"
  public-02:
    cidr: 10.0.4.0/24
    az: "{{ aws_region }}b"
  private-03:
    cidr: 10.0.5.0/24
    az: "{{ aws_region }}c"
  public-03:
    cidr: 10.0.6.0/24
    az: "{{ aws_region }}c"

# a list defining the security groups for our VPC
vpc_security_groups:
  - name: vpc
    description: "Allow internal traffic in the VPC"
    rules:
      - proto: all
        group_name: vpc
        ports:
          - 22
          - 80
          - 443
          - 5432
          - 8080-8099
  - name: allow-public-ssh
    description: "Allow public SSH"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 22
  - name: allow-public-http
    description: "Allow public web traffic"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 80
          - 443
