---
- hosts: localhost
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_REGION: "{{ aws_region }}"

  roles:
    - { role: iam, tags: iam }
    - { role: vpc, tags: vpc }
    - { role: rds, tags: rds }
    - { role: sss, tags: sss }
    - { role: cdn, tags: cdn }
    - { role: dns, tags: dns }
    - { role: acm, tags: acm }
    - { role: cfg, tags: cfg }
