---
- hosts: localhost
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_REGION: "{{ aws_region }}"

  roles:
    # run these roles in this order when state is "present"
    - { role: "vpc", when: (ecs_state == 'present') }
    - { role: "rds", when: (ecs_state == 'present') }
    # - { role: "elb", when: (ecs_state == 'present') }
