- name: Configure CDN distribution for serving media over HTTPS
  cloudfront_distribution:
    alias: "{{ media_cname }}"
    comment: "{{ media_cname }} distribution"
    default_cache_behavior:
      viewer_protocol_policy: redirect-to-https
      target_origin_id: "{{ media_cname }}-cdn"
      forwarded_values:
        query_string: true
        cookies:
          forward: all
    enabled: yes
    http_version: http2
    origins:
      - id: "{{ media_cname }}-cdn"
        domain_name: "{{ media_cname }}.s3.amazonaws.com"
        s3_origin_access_identity_enabled: yes
    purge_tags: yes
    state: present
    wait: yes
    tags:
      Service: "{{ service_name }}"
      Name: "{{ media_cname }}-cdn"
      Environment: "{{ elektron_env }}"
    viewer_certificate:
        acm_certificate_arn: "{{ https_certificate_arn }}"
        ssl_support_method: sni-only
