- name: Configure CDN distribution for serving media over HTTPS
  cloudfront_distribution:
    alias: "{{ media_cname }}"
    default_root_object: index.html
    enabled: yes
    http_version: http2
    origins:
      - id: "S3-{{ media_cname }}"
        domain_name: "{{ media_cname }}.s3.amazonaws.com"
        s3_origin_access_identity_enabled: yes
    purge_tags: yes
    state: present
    tags:
      Service: "{{ service_name }}"
      Name: "{{ media_cname }}-cdn"
    viewer_certificate:
        acm_certificate_arn: "{{ https_certificate_arn }}"
        ssl_support_method: sni-only
