---
# confirm existence of auth key
- name: create EC2 key
  ec2_key:
    name: "{{ aws_ssh_key }}"

- name: Create a photo processor role with description
  iam_role:
    name: "{{ photo_processor_rolename }}"
    managed_policy:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
    assume_role_policy_document:
      Version: '2012-10-17'
      Statement:
      - Effect: Allow
        Principal:
          Service:
          - lambda.amazonaws.com
        Action:
        - sts:AssumeRole
    description: Photo processor role
  register: photo_processor_role_info

- name: Associate r/o media bucket permissions with photo processor role
  iam_policy:
    iam_type: role
    iam_name: "{{ photo_processor_rolename }}"
    policy_name: "{{operating_env}}-{{service_name}}-PhotoProcessorPolicy"
    policy_json:
      Version: '2012-10-17'
      Statement:
      - Effect: Allow
        Action:
        - s3:Get*
        - s3:List*
        Resource:
        - arn:aws:s3:::{{media_upload_bucket_name}}
        - arn:aws:s3:::{{media_upload_bucket_name}}/*
    state: present
  register: result

- name: set photo processor role arn as fact
  set_fact:
    photo_processor_role_arn: "{{ photo_processor_role_info.iam_role.arn }}"

- name: Create a role that allows API Gateway to write to Cloudwatch
  iam_role:
    name: "{{ api_gateway_logging_rolename }}"
    managed_policy:
      - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
    assume_role_policy_document:
      Version: '2012-10-17'
      Statement:
      - Effect: Allow
        Principal:
          Service:
          - apigateway.amazonaws.com
        Action:
        - sts:AssumeRole
    description: Allow API Gateway to write to Cloudwatch
  register: api_gateway_logging_role_info

- name: set API gateway logging role arn as fact
  set_fact:
    api_gateway_logging_role_arn: "{{ api_gateway_logging_role_info.iam_role.arn }}"

- name: Create a lambda execution role
  iam_role:
    name: "{{ lambda_execution_rolename }}"
    managed_policies:
      - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      - arn:aws:iam::aws:policy/AmazonSESFullAccess
    assume_role_policy_document:
      Version: '2012-10-17'
      Statement:
      - Effect: Allow
        Principal:
          Service:
          - lambda.amazonaws.com
        Action:
        - sts:AssumeRole
    description: Lambda execution role
  register: lambda_execution_role_info

- name: Ensure lambda has authorization to write to media bucket
  iam_policy:
    policy_name: "{{ service_name }}-{{ operating_env }}-media-put"
    iam_name: "{{ lambda_execution_rolename }}"
    iam_type: role
    policy_json:
      Version: "2012-10-17"
      Statement:
        - Sid: Created20200209
          Effect: Allow
          Action:
          - s3:PutObject
          - s3:GetObject
          Resource: "arn:aws:s3:::{{ media_upload_bucket_name }}/*"
        - Sid: Created20200210
          Effect: Allow
          Action:
          - s3:PutObject
          - s3:GetObject
          - s3:ListBucket
          Resource:
          - "arn:aws:s3:::{{ media_thumbnail_bucket_name }}"
          - "arn:aws:s3:::{{ media_thumbnail_bucket_name }}/*"
    state: present

- name: set lambda execution role arn as fact
  set_fact:
    lambda_execution_role_arn: "{{ lambda_execution_role_info.iam_role.arn }}"
