---
# confirm existence of auth key
- name: create EC2 key
  ec2_key:
    name: "{{ aws_ssh_key }}"

- import_tasks: application-service.yml
- import_tasks: media-processor.yml
- import_tasks: thumbnail-service.yml
