# Generated by Django 2.1.4 on 2019-01-22 01:48

import collection.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('path', models.CharField(error_messages={'unique': 'A collection with that path already exists.'}, help_text='Required. Path to media collection from the root of your archive.', max_length=1024, unique=True, validators=[collection.models.CollectionPathValidator()], verbose_name='collection path')),
            ],
            options={
                'db_table': 'collection',
            },
        ),
    ]
