# Generated by Django 2.1.4 on 2019-01-25 15:00

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20190122_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='path',
            field=models.CharField(help_text='Required. Path to media collection from the root of your archive.', max_length=1024, validators=[collection.models.CollectionPathValidator()], verbose_name='collection path'),
        ),
    ]
