# Generated by Django 2.1.4 on 2019-01-11 11:17

from django.db import migrations

def default_username(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    for row in CustomUser.objects.all():
        if row.username == None or row.username == '':
            row.username = row.email
            row.save(update_fields=['username'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190106_1334'),
    ]

    operations = [
        migrations.RunPython(default_username, reverse_code=migrations.RunPython.noop),
    ]
