# Generated by Django 2.1.4 on 2019-01-13 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190111_1120'),
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"'),
        migrations.RunSQL("ALTER TABLE users_customuser_groups DROP COLUMN customuser_id"),
        migrations.RunSQL("ALTER TABLE users_customuser_groups ADD COLUMN customuser_id UUID"),

        migrations.RunSQL("ALTER TABLE users_customuser_user_permissions DROP COLUMN customuser_id"),
        migrations.RunSQL("ALTER TABLE users_customuser_user_permissions ADD COLUMN customuser_id UUID"),

        migrations.RunSQL("ALTER TABLE users_customuser ADD COLUMN _id uuid NOT NULL UNIQUE DEFAULT uuid_generate_v4()"),

        migrations.RunSQL("ALTER TABLE django_admin_log ADD COLUMN _user_id UUID"),
        migrations.RunSQL("UPDATE django_admin_log AS dest SET _user_id = (SELECT _id FROM users_customuser uc WHERE uc.id = dest.user_id)"),
        migrations.RunSQL("ALTER TABLE django_admin_log ALTER COLUMN _user_id SET NOT NULL"),
        migrations.RunSQL("ALTER TABLE django_admin_log DROP COLUMN user_id"),
        migrations.RunSQL("ALTER TABLE django_admin_log RENAME COLUMN _user_id TO user_id"),

        migrations.RunSQL("ALTER TABLE socialaccount_socialaccount ADD COLUMN _user_id UUID"),
        migrations.RunSQL("UPDATE socialaccount_socialaccount AS dest SET _user_id = (SELECT _id FROM users_customuser uc WHERE uc.id = dest.user_id)"),
        migrations.RunSQL("ALTER TABLE socialaccount_socialaccount ALTER COLUMN _user_id SET NOT NULL"),
        migrations.RunSQL("ALTER TABLE socialaccount_socialaccount DROP COLUMN user_id"),
        migrations.RunSQL("ALTER TABLE socialaccount_socialaccount RENAME COLUMN _user_id TO user_id"),

        migrations.RunSQL("ALTER TABLE account_emailaddress ADD COLUMN _user_id UUID"),
        migrations.RunSQL("UPDATE account_emailaddress AS dest SET _user_id = (SELECT _id FROM users_customuser uc WHERE uc.id = dest.user_id)"),
        migrations.RunSQL("ALTER TABLE account_emailaddress ALTER COLUMN _user_id SET NOT NULL"),
        migrations.RunSQL("ALTER TABLE account_emailaddress DROP COLUMN user_id"),
        migrations.RunSQL("ALTER TABLE account_emailaddress RENAME COLUMN _user_id TO user_id"),

        migrations.RunSQL("ALTER TABLE users_customuser DROP COLUMN id"),
        migrations.RunSQL("ALTER TABLE users_customuser RENAME COLUMN _id TO id"),
        migrations.RunSQL("ALTER TABLE users_customuser ADD PRIMARY KEY (id)"),

        migrations.RunSQL("ALTER TABLE django_admin_log ADD CONSTRAINT django_admin_log_customuser_fk FOREIGN KEY (user_id) REFERENCES users_customuser (id)"),
        migrations.RunSQL("ALTER TABLE socialaccount_socialaccount ADD CONSTRAINT socialaccount_socialaccount_customuser_fk FOREIGN KEY (user_id) REFERENCES users_customuser (id)"),
        migrations.RunSQL("ALTER TABLE account_emailaddress ADD CONSTRAINT account_emailaddress_customuser_fk FOREIGN KEY (user_id) REFERENCES users_customuser (id)"),
    ]
