# Generated by Django 4.2.16 on 2024-11-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processorlog',
            name='original_file_path',
            field=models.CharField(
                blank=True,
                help_text='Optional. Path to media item that was uploaded.',
                max_length=4096,
                null=True,
                verbose_name='Original file path',
            ),
        ),
        migrations.AlterField(
            model_name='processorlog',
            name='reason',
            field=models.CharField(
                blank=True,
                help_text='Optional. Reason for the error, e.g. stacktrace.',
                max_length=8192,
                null=True,
                verbose_name='Error reason',
            ),
        ),
    ]
