# Generated by Django 2.2.12 on 2020-04-10 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sharing.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='shared_by',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='audience',
            name='unsubscribed',
            field=models.BooleanField(
                default=False,
                verbose_name="Whether this email's owner has requested to be unsubscribed for this user.",
            ),
        ),
        migrations.AddField(
            model_name='share',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='share',
            name='message',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='share',
            name='subject',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='audience', name='email', field=models.EmailField(max_length=512)
        ),
        migrations.AlterField(
            model_name='share',
            name='state',
            field=models.CharField(
                choices=[('initial', 'Initial'), ('draft', 'Draft'), ('shared', 'Shared')],
                default=sharing.models.ShareState('initial'),
                max_length=24,
            ),
        ),
        migrations.AlterUniqueTogether(name='audience', unique_together={('email', 'shared_by')}),
    ]
