# Generated by Django 2.2.12 on 2020-04-06 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [('sharing', '0002_auto_20200405_1310')]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='unsubscribed',
            field=models.BooleanField(
                default=False,
                verbose_name="Whether this email's owner has requested to be unsubscribed for this user.",
            ),
        ),
        migrations.AlterField(
            model_name='audience',
            name='shared_by',
            field=models.ForeignKey(
                default=uuid.uuid4,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
