---
- name: "Create NAT instance for {{ item.key }}"
  ec2:
    assign_public_ip: yes
    group: "{{ vpc_name }}-nat-sg"
    image: "{{ nat_instance_ami }}"
    instance_tags:
      Service: "{{ service_name }}"
      Name: "ec2-nat-{{ item.key }}"
      Environment: "{{ elektron_env }}"
    exact_count: 1
    count_tag: 
      Name: "ec2-nat-{{ item.key }}"
      Environment: "{{ elektron_env }}" # necessary?
    instance_type: "{{ nat_instance_type }}"
    key_name: "{{ aws_ssh_key }}"
    source_dest_check: no
    vpc_subnet_id: "{{ item.value }}"
    wait: yes
  register: ec2

- set_fact:
    ec2_query: "tagged_instances[?tags.Name == 'ec2-nat-{{ item.key }}'].id"

- debug:
    var: ec2_query

- name: "Create NAT routing table entry for {{ item.key }}"
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    tags:
      Service: "{{ service_name }}"
      Name: "{{ vpc_name }}-nat-private"
      Environment: "{{ elektron_env }}"
    subnets:
      - "{{ vpc_subnet_ids['private-01'] }}"
      - "{{ vpc_subnet_ids['private-02'] }}"
    routes:
      - dest: 0.0.0.0/0
        # this json_query returns a one element array that needs to be converted to a string
        instance_id: "{{ ec2 | json_query(ec2_query) | join('') }}"
