# tasks/vpc/setup.vpc.yml
# ---
# creates a VPC, configures a list of defined subnets, configures a list of defined security groups

- import_tasks: vpc.yml
- import_tasks: subnets.yml
- import_tasks: security_groups.yml
- import_tasks: internet_gateway.yml
- import_tasks: routing_tables.yml

# Configure and launch NAT instances for each public subnet
- include_tasks: create_nat_instance.yml
  loop: "{{ vpc_subnet_ids | dict2items | selectattr('key', 'match', '^public') | list }}"
  loop_control:
    loop_var: item
