# host_vars/elektron.vpc.yml

# a list defining the security groups for our VPC
vpc_security_groups:
  - name: "{{ vpc_name }}-public-sg"
    description: "Allow public HTTP & limited public SSH"
    rules:
      - proto: tcp
        cidr_ip: "{{ home_ip }}/32"
        ports:
          - 22
        rule_desc: "Home"
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 80
          - 443
  - name: "{{ vpc_name }}-private-sg"
    description: "Allow traffic to PSQL from NAT (in public subnets) & Lambdas (in private subnets)"
    rules:
      - proto: tcp
        cidr_ip:  "{{ vpc_subnet_cidrs['public-01'] }}"
        ports:
          - 5432
        rule_desc: "Access PSQL from public subnet."
      - proto: tcp
        cidr_ip:  "{{ vpc_subnet_cidrs['public-02'] }}"
        ports:
          - 5432
        rule_desc: "Access to PSQL from public subnet."
      - proto: tcp
        cidr_ip:  "{{ vpc_subnet_cidrs['private-01'] }}"
        ports:
          - 5432
        rule_desc: "Access PSQL from private subnet."
      - proto: tcp
        cidr_ip:  "{{ vpc_subnet_cidrs['private-02'] }}"
        ports:
          - 5432
        rule_desc: "Access to PSQL from private subnet."
  - name: "{{ vpc_name }}-nat-sg"
    description: "Configure access rules for NAT instance & Lambda."
    rules:
      - proto: tcp
        cidr_ip:  "{{ vpc_subnet_cidrs['private-01'] }}"
        ports:
          - 80
          - 443
        rule_desc: "Access to HTTP/S from private subnet."
      - proto: tcp
        cidr_ip:  "{{ vpc_subnet_cidrs['private-02'] }}"
        ports:
          - 80
          - 443
        rule_desc: "Access to HTTP/S from private subnet."
      - proto: tcp
        cidr_ip: "{{ home_ip }}/32"
        ports:
          - 22
        rule_desc: "SSH access from Home"

