# host_vars/elektron.vpc.yml

vpc_name: "{{elektron-env}}-elektron-vpc"

vpc_cidr_block: 10.0.0.0/16

vpc_subnets:
  private-01:
    cidr: 10.0.1.0/24
    az: "{{ aws_region }}a"
    visibility: private
  public-01:
    cidr: 10.0.2.0/24
    az: "{{ aws_region }}a"
    visibility: public
  private-02:
    cidr: 10.0.3.0/24
    az: "{{ aws_region }}b"
    visibility: private
  public-02:
    cidr: 10.0.4.0/24
    az: "{{ aws_region }}b"
    visibility: public

# a list defining the security groups for our VPC
vpc_security_groups:
  - name: "{{ vpc_name }}-public-sg"
    description: "Allow public HTTP & limited public SSH"
    rules:
      - proto: tcp
        cidr_ip: "{{ home_ip }}/32"
        ports:
          - 22
        rule_desc: "Home"
      - proto: tcp
        cidr_ip: "152.179.78.138/32"
        ports:
          - 22
        rule_desc: "Work"
      - proto: tcp
        cidr_ip: "72.69.147.155/32"
        ports:
          - 22
        rule_desc: "Cafe"
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 80
          - 443
  - name: "{{ vpc_name }}-private-sg"
    description: "Allow traffic to PSQL from NAT (in public subnets) & Lambdas (in private subnets)"
    rules:
      - proto: tcp
        cidr_ip:  "{{ vpc_subnet_cidrs['public-01'] }}"
        ports:
          - 5432
        rule_desc: "Access PSQL from public subnet."
      - proto: tcp
        cidr_ip:  "{{ vpc_subnet_cidrs['public-02'] }}"
        ports:
          - 5432
        rule_desc: "Access to PSQL from public subnet."
      - proto: tcp
        cidr_ip:  "{{ vpc_subnet_cidrs['private-01'] }}"
        ports:
          - 5432
        rule_desc: "Access PSQL from private subnet."
      - proto: tcp
        cidr_ip:  "{{ vpc_subnet_cidrs['private-02'] }}"
        ports:
          - 5432
        rule_desc: "Access to PSQL from private subnet."
  - name: "{{ vpc_name }}-nat-sg"
    description: "Configure access rules for NAT instance & Lambda."
    rules:
      - proto: tcp
        cidr_ip:  "{{ vpc_subnet_cidrs['private-01'] }}"
        ports:
          - 80
          - 443
        rule_desc: "Access to HTTP/S from private subnet."
      - proto: tcp
        cidr_ip:  "{{ vpc_subnet_cidrs['private-02'] }}"
        ports:
          - 80
          - 443
        rule_desc: "Access to HTTP/S from private subnet."
      - proto: tcp
        cidr_ip: "{{ home_ip }}/32"
        ports:
          - 22
        rule_desc: "SSH access from Home"

