# Generated by Django 2.2.9 on 2020-03-20 11:43

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_items', '0008_auto_20190512_1011'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    ),
                ),
                ('email', models.EmailField(max_length=512, unique=True)),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='AudienceShare',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                )
            ],
        ),
        migrations.CreateModel(
            name='MediaShare',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                )
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    ),
                ),
                (
                    'state',
                    models.CharField(
                        choices=[(10, 'draft'), (30, 'shared')], default=10, max_length=24
                    ),
                ),
                (
                    'shared_on',
                    base.models.DateTimeNoTZField(
                        help_text='The date and time these media items were shared.',
                        null=True,
                        verbose_name='share date',
                    ),
                ),
                (
                    'shared',
                    models.ManyToManyField(
                        through='sharing.MediaShare', to='media_items.MediaItem'
                    ),
                ),
                (
                    'shared_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'shared_to',
                    models.ManyToManyField(through='sharing.AudienceShare', to='sharing.Audience'),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.AddField(
            model_name='mediashare',
            name='share',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='sharing.Share'
            ),
        ),
        migrations.AddField(
            model_name='mediashare',
            name='shared_media',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='media_items.MediaItem'
            ),
        ),
        migrations.AddField(
            model_name='audienceshare',
            name='share',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='sharing.Share'
            ),
        ),
        migrations.AddField(
            model_name='audienceshare',
            name='shared_to',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='sharing.Audience'
            ),
        ),
    ]
