# Generated by Django 2.1.7 on 2019-04-22 00:04

# import django.contrib.gis.db.models.fields
from django.db import migrations, models
import media_items.models


class Migration(migrations.Migration):

    dependencies = [('media_items', '0003_auto_20190406_0128')]

    operations = [
        migrations.RenameField(model_name='mediaitem', old_name='media_type', new_name='mime_type'),
        migrations.AddField(
            model_name='mediaitem',
            name='artist',
            field=models.CharField(
                help_text='Optional. Artist responsible for creating this media item.',
                max_length=64,
                null=True,
                verbose_name='artist',
            ),
        ),
        # migrations.AddField(
        #     model_name='mediaitem',
        #     name='gps_location',
        #     field=django.contrib.gis.db.models.fields.PointField(dim=3, help_text='Optional. The coordinate for the GPS location of where this media item was created.', null=True, srid=4326, verbose_name='gps coordinate'),
        # ),
        migrations.AddField(
            model_name='mediaitem',
            name='shutter_speed',
            field=models.CharField(
                help_text='Optional. The shutter speed setting used when this media item was created.',
                max_length=16,
                null=True,
                verbose_name='shutter speed',
            ),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='create_date',
            field=media_items.models.DateTimeNoTZField(
                help_text='Required. The date and time this media item was created.',
                verbose_name='create date',
            ),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='file_size',
            field=models.BigIntegerField(
                help_text='Required. The size in bytes of the media item.',
                null=True,
                verbose_name='file size',
            ),
        ),
    ]
