# Generated by Django 2.1.7 on 2019-05-12 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('media_items', '0007_mediaitem_create_day')]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='create_day',
            field=models.ForeignKey(
                help_text='The date the media item was created.',
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='date_dimension.DateDimension',
            ),
        )
    ]
