name: elektrum-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      OPERATING_ENV: ci
      GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install toml
        etc/bin/poetry2pip.py --file poetry.lock --dev-deps > requirements.txt
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd functions/application
        python manage.py test
