---
- name: Output service name
  lineinfile:
    path: "{{ config_info }}"
    regexp: '^service_name="{{ service_name }}"'
    line: 'service_name="{{ service_name }}"'

- name: Output app name
  lineinfile:
    path: "{{ config_info }}"
    regexp: '^app_name="{{ app_name }}"'
    line: 'app_name="{{ app_name }}"'

- name: Output org name
  lineinfile:
    path: "{{ config_info }}"
    regexp: '^org_name="{{ org_name }}"'
    line: 'org_name="{{ org_name }}"'

- name: Output db host info
  lineinfile:
    path: "{{ config_info }}"
    regexp: '^db_hostname="{{ db_endpoint_url }}"'
    line: 'db_hostname="{{ db_endpoint_url }}"'

- name: store db port info
  lineinfile:
    path: "{{ config_info }}"
    regexp: '^db_port_num="{{ db_port_number }}"'
    line: 'db_port_num="{{ db_port_number }}"'

- name: store db instance info
  lineinfile:
    path: "{{ config_info }}"
    regexp: '^db_instance="{{ db_instance }}"'
    line: 'db_instance="{{ db_instance }}"'

- name: store db name
  lineinfile:
    path: "{{ config_info }}"
    regexp: '^db_name="{{ db_name }}"'
    line: 'db_name="{{ db_name }}"'

- name: store username
  lineinfile:
    path: "{{ config_info }}"
    regexp: '^db_username="{{ db_username }}"'
    line: 'db_username="{{ db_username }}"'

- name: store vpc info (id)
  lineinfile:
    path: "{{ config_info }}"
    regexp: '^vpc_id="{{ vpc_id }}"'
    line: 'vpc_id="{{ vpc_id }}"'

- set_fact:
    sn_ids="{{ public_subnet_ids|join(',') }}"

- name: store vpc info (subnet ids)
  lineinfile:
    path: "{{ config_info }}"
    regexp: '^vpc_public_subnet_ids="{{ sn_ids }}"'
    line: 'vpc_public_subnet_ids="{{ sn_ids }}"'

- name: store vpc info (security group id)
  lineinfile:
    path: "{{ config_info }}"
    regexp: '^vpc_security_group_ids="{{ public_security_group_id }}"'
    line: 'vpc_security_group_ids="{{ public_security_group_id }}"'
